### ISSUE TITLE
AC3 not working with internal player

### ISSUE THREAD

**Issue by MASHtm** [sreichholf/dreamDroid#100]
if I use the internal player everything works fine ... SD/mpeg, HD/h264, MPEG Audio, ... but not AC3. Most notable on channels which only have AC3 audio. using external VLC works as usual on my Samsung A3 2016. Source is my 7020HD. dreamdroid is self built master/1.2-401 was up2date Android Studio/SDK

**Comment by sreichholf** [comment]
There is some heavy work going on with the player currently, feel free to subscribe as beta-tester.
But be warned, things break on betas and on intense days i'll push out 2-3 updates in a row.

If you don't want that, you probably don't have to wait THAT much longer.

**Comment by sreichholf** [comment]
Did the new player help with this for you? It's been out for while now!
