### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by Poussinou** [sreichholf/dreamDroid#105]
Can you please tag your recent releases (see [here](https://help.github.com/articles/creating-releases/)), it would be helpful for the F-Droid release (Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/429)). You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)).

That's pretty easy and very helpful for those of us who aren't using Google services.

**Comment by sreichholf** [comment]
Done for 1.2-403 :)

**Comment by Poussinou** [comment]
Cool :) do not forget to do it for next releases, so that we can have automatic updates via F-Droid ;)
