### ISSUE TITLE
virtual remote as default after opening app

### ISSUE THREAD

**Issue by GuitarBilly** [sreichholf/dreamDroid#135]
v1.5.438 (latest via Google Play) on android 7.1.2 and 6.0

hello,
i am using DreamDroid for many years and it works great. Lately i use more and more the Virtual Remote function. Is there a way to set the configuration to show the Virtual Remote at startup? I could not find it in the settings.

**Comment by basalt79** [comment]
For this scenario, I always use the widget.

**Comment by GuitarBilly** [comment]
Excellent suggestion, but the widget only appears as "simple remote" while i use the additional buttons from "advanced remote" layout. Making that one available as widget could be another solution.

**Comment by basalt79** [comment]
@GuitarBilly  if you add the widget to the screen, you will get the option if you want to have the simple or the enhanced mode.
so there you can change to enhanced mode also for the widget

**Comment by GuitarBilly** [comment]
@basalt79 thanks again for replying. So my original question is resolved, i can now use the widget instead of launching the app.

I never knew it works like this. Not only because i had the widget already in place in the simple layout. But on my two phones (v1.5.438 on android 7.1.2 and 6.0) i get a blank dialog with only a tickbox, when disabled it created the big remote layout. 


Let me add the screenshot of my widget dialog  for the designers :
![Screenshot_20210105-144120](https://user-images.githubusercontent.com/38086529/103653430-d0014480-4f64-11eb-8f5d-606224d25c93.png)

**Comment by basalt79** [comment]
@GuitarBilly i can reproduce the issue also on my device, can you create a dedicated ticket for this issue pls.
thx for the finding.

**Comment by GuitarBilly** [comment]
done. this one can go to the archives.
