### ISSUE TITLE
Virtual Remote PLAYPAUSE instead of PLAY button option

### ISSUE THREAD

**Issue by GuitarBilly** [sreichholf/dreamDroid#136]
v1.5.438 (latest via Google Play) on android 7.1.2 and 6.0

hello again,
when using the Virtual Remote from DreamDroid, its big layout looks similar with buttons to my real Dreambox remote. However it acts different in one way :  the PLAY button. 

On the real advanced Dreambox control (DM500HD/DM800HD/DM8000) the PLAY button in the row with PREV and STOP and NEXT is actually a combined PLAY/PAUSE button. This is used to start and pause TimeShift recording.
The Virtual Remote on DreamDroid cannot start or pause timeshift as i guess it acts as KEY_PLAY instead of KEY_PLAYPAUSE.

It would be great if one can configure the key and/or key binding from DreamDroid to match this real world advanced Dreambox remote control functionality.

picture of the remote:
![DreamBox_remote](https://user-images.githubusercontent.com/38086529/103593208-7877c000-4ef5-11eb-9967-e495916e99ed.jpg)

**Comment by basalt79** [comment]
i will give it a try, currently i use the Play button for PLAY and PAUSE the recorded movie, and for this it is working as on the real remote.
but  @GuitarBilly you are right, the assigned action is KEY_PLAY, i will try to make it configurable in the settings part of the app

**Comment by GuitarBilly** [comment]
hello @basalt79 @sreichholf, i see this feature was accepted last year but i can not find it in the app?
Timeline shows 3 releases since Oct 2021.
Hope any of you can clarify.

**Comment by sreichholf** [comment]
Hey, yeah unfortunately there hasn't been an official release since.
My spare time for this project is very, very limited that's why things get delayed more and more...

**Comment by GuitarBilly** [comment]
hello, stoked to see a new dreamdroid release today with this feature in the settings.

i can confirm the feature works for the app as well as the widget. now i can operate 100% of the real remote with dreamdroid! thanks again @basalt79 and @sreichholf.

one note: i did not see this added feature in the release description.

**Comment by sreichholf** [comment]
I actually missed adding this to the changelog...
