### ISSUE TITLE
no text or buttons in dialog when adding widget

### ISSUE THREAD

**Issue by GuitarBilly** [sreichholf/dreamDroid#137]
v1.5.438 (latest via Google Play) on android 7.1.2 and 6.0

hello,
when adding the DreamDroid widget there appears an empty dialog with a single tickbox.
This can be reproduced on two of my two phones and also by basalt79 as referenced in item #135.
Myself i am using the Nova Launcher on both phones, that could be relevant.

The dialog looks like this : 
![dreamdroid_dialog](https://user-images.githubusercontent.com/38086529/103692149-a7df0900-4f97-11eb-9397-39143c4ed0ba.png)

As an end user i would expect to be guided by some text and/or buttons to support the choice for the simple and advanced remote layout for the widget.
Hope this helps.

**Comment by basalt79** [comment]
thx @GuitarBilly  I will have a look

**Comment by basalt79** [comment]
Fixed in #137 waiting for merge. Hope this helps.

**Comment by GuitarBilly** [comment]
i can confirm that this is resolved. 
issue can be closed.
