### ISSUE TITLE
dreamdroid.org redirects to advertising pages

### ISSUE THREAD

**Issue by cweiske** [sreichholf/dreamDroid#148]
https://dreamdroid.org/de/ redirects my browser to many advertising pages until it closes the tab and opens a new google.com tab.

Has the wordpress instance it been hacked?

----

URLs I saw:
- https://chess.storerightdesicion.com/go.php?id=79699-347-3485623-44
- https://usebellyfeilicia.best/

**Comment by sreichholf** [comment]
Oh boy, thx for telling me!

**Comment by sreichholf** [comment]
Just FYI. This was an XSS vulnerability in the WP DSGVO Plugin.
Everything has been updated and fixed. 
Again: Thank you!

**Comment by cweiske** [comment]
Thanks for the explanation.
