### ISSUE TITLE
A confusing widget on "dreamDroid" 's UI

### ISSUE THREAD

**Issue by b450mhdv** [sreichholf/dreamDroid#149]
Hello @sreichholf  , I enjoy using this app, it is very useful for me! However, I found a misleading widget in this app. When the app encounters problems (such as no network), a prompt box will pop up at the bottom. However, personally, I think the "More" button in the prompt box might not be more appropriate than "Detail". Because I can find a lot of prompt boxes with the text "Detail" in other popular apps.
So, for improving the user experience, could you try to redesign the widget? And thanks for your useful app!
<img src="https://user-images.githubusercontent.com/78015408/167302394-375a2c62-1e22-4599-9016-313fc2503936.jpg" width="300px"/>

**Comment by sreichholf** [comment]
Good suggestion, I'll change that!

**Comment by sreichholf** [comment]
This is fixed in 1.6 betas
