### ISSUE TITLE
No updates on F-droid and Playstore

### ISSUE THREAD

**Issue by MasterPlexus** [sreichholf/dreamDroid#153]
Hi,

Is there a reason why the version on the Markets are pretty old, but I can see several comments in between? 

No problem to build it by own, but as far as I remember if a new asset will be done, then F-droid will be also actualized automatically as far as I remember... Or are there some unclear/untested commits within?

Br
MP

**Comment by sreichholf** [comment]
Yes,

I haven't tagged any new release by now because, as always, I'm only working on this app when I "feel like it".
There is beta releases on the play store if you go and sign up for beta testing, though.

**Comment by MasterPlexus** [comment]
So I activated the beta in Google PS, and get newer versions, which looks like better. Thanks for the hint, and of course for the work done !
