### ISSUE TITLE
Latest release crashes on Fire TV when trying to stream

### ISSUE THREAD

**Issue by petrm** [sreichholf/dreamDroid#156]
Hi,
The Fire TV version got updated two days ago and since then it doesn't work. It crashes as soon as you select a channel to stream. Downgrading to an older version from the releases here works.
Looking at logcat there seems to be a problem caused by the new PIP feature:
```
E/AndroidRuntime(17750): FATAL EXCEPTION: main                                                                                                                                
E/AndroidRuntime(17750): Process: net.reichholf.dreamdroid.amazon, PID: 17750                                                                                                 
E/AndroidRuntime(17750): java.lang.NoSuchMethodError: No virtual method isInPictureInPictureMode()Z in class Landroid/app/Activity; or its super classes (declaration of 'andr
oid.app.Activity' appears in /system/framework/framework.jar)                                                                                                                 
E/AndroidRuntime(17750):        at net.reichholf.dreamdroid.fragment.VideoOverlayFragment.b1(SourceFile:5)                                                                    
E/AndroidRuntime(17750):        at net.reichholf.dreamdroid.fragment.VideoOverlayFragment.Y0(SourceFile)                                                                      
E/AndroidRuntime(17750):        at net.reichholf.dreamdroid.fragment.VideoOverlayFragment.z0(SourceFile)                                                             
E/AndroidRuntime(17750):        at androidx.fragment.app.n0.f(SourceFile:254)
E/AndroidRuntime(17750):        at androidx.fragment.app.n0.k(SourceFile:146)
E/AndroidRuntime(17750):        at androidx.fragment.app.h0.B(SourceFile:25)
E/AndroidRuntime(17750):        at androidx.fragment.app.h0.Y(SourceFile)
E/AndroidRuntime(17750):        at androidx.fragment.app.h0.z(SourceFile:74)
E/AndroidRuntime(17750):        at androidx.fragment.app.h0.u(SourceFile:65)
E/AndroidRuntime(17750):        at androidx.fragment.app.v.onStart(SourceFile:32)
E/AndroidRuntime(17750):        at androidx.appcompat.app.h.onStart(SourceFile)
E/AndroidRuntime(17750):        at net.reichholf.dreamdroid.activities.VideoActivity.onStart(SourceFile:1)
E/AndroidRuntime(17750):        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1252)
E/AndroidRuntime(17750):        at android.app.Activity.performStart(Activity.java:6054)
E/AndroidRuntime(17750):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
E/AndroidRuntime(17750):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2563)
E/AndroidRuntime(17750):        at android.app.ActivityThread.access$900(ActivityThread.java:168)
E/AndroidRuntime(17750):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1336)
E/AndroidRuntime(17750):        at android.os.Handler.dispatchMessage(Handler.java:102) 
E/AndroidRuntime(17750):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(17750):        at android.app.ActivityThread.main(ActivityThread.java:5619)
E/AndroidRuntime(17750):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17750):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17750):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
E/AndroidRuntime(17750):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by sreichholf** [comment]
Hey, this will be fixed in the next release!

**Comment by sreichholf** [comment]
A quick heads up: 
The fixed version is still under review by amazon (for >2 days now). 
We can't do anyhting but wait for amazon to finish the review, sorry!

**Comment by sreichholf** [comment]
The fix for this is now available on the amazon app store.
Feedback would be highly regarded!

**Comment by petrm** [comment]
I am not able to update the app from the amazon store. After trying uninstalling I was no longer able to find it. Then I went to the computer to the store and fire tv is not listed in the compatible devices anymore.

**Comment by sreichholf** [comment]
Oh wow... Thats bad. I'll try to take care of that asap...Von: Petr Man ***@***.***>Gesendet: Freitag, 27. Januar 2023 18:02An: sreichholf/dreamDroidCc: reichi; CommentBetreff: Re: [sreichholf/dreamDroid] Latest release crashes on Fire TV when trying to stream (Issue #156) 
I am not able to update the app from the amazon store. After trying uninstalling I was no longer able to find it. Then I went to the computer to the store and fire tv is not listed in the compatible devices anymore.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/sreichholf/dreamDroid/issues/156#issuecomment-1406791033",
"url": "https://github.com/sreichholf/dreamDroid/issues/156#issuecomment-1406791033",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sreichholf** [comment]
Here's a short update about this issue:

Amazon really fu***d it up there.
After releasing the latest version the tester noted that video playback doesn’t work for him and removed the app compatiblity for all FireTV devices.
I have opened a ticket with amazon explaining that it would stay that way unless the set up a dreambox and hope this is easily resolvable...
If not I have to create some pseudo Bick-Buck-Bunny testing backend just for amazon to be happy (and I REALLY don't want to).

**Comment by sreichholf** [comment]
I just got positive feedback:

> "Thank you for providing additional information. We are pleased to confirm that your App has been approved and will go live within 48hrs."

DreamDroid is already live for FireTV again!
