### ISSUE TITLE
Signal font color in night theme

### ISSUE THREAD

**Issue by angelheart150** [sreichholf/dreamDroid#160]
Please change font color in signal meter it is black in black background (night theme). We can't see the signal under indicator. It can be yellow or white to be readable.

![Screenshot_2023-07-20-09-26-33-347_net.reichholf.dreamdroid-edit.jpg](https://github.com/sreichholf/dreamDroid/assets/67199651/3ddddfd3-e254-434c-917e-643fd3ee2767)

**Comment by sreichholf** [comment]
This will be fixed in the upcoming bugfix release
