### ISSUE TITLE
Recording timers can't be modified

### ISSUE THREAD

**Issue by Calico** [sreichholf/dreamDroid#70]
Hello,
I have a problem with recording timers. Maybe you are already aware of this :

If I try to adjust the end of a recording timer, for example if I want it to end it 20 minutes later, I have a pop-up telling me "Internal server error". Of course, the timer doesn't change.

I'm using a Vu+ Uno running OpenPLi 4.0 image (Openwebif).

Don't hesitate to contact me if you need me to do some tests.

**Comment by sreichholf** [comment]
Pretty much for sure an issue with obenwebif (which is not supported by dreamDroid other than "may work, may not"
