### ISSUE TITLE
any plans to support android tv

### ISSUE THREAD

**Issue by chemstar** [sreichholf/dreamDroid#73]
hi stephan, do you have any plans to support android tv's channels feature? 
it would be great addition to dreamdroid when some channels/boquets could be selected and exported to android tv's channels. as i could see dreamdroid already include a lot of the needed code (complete framework for channels/boquets/epg etc. handling). 

some additional informations (if needed/wanted):
https://developer.android.com/training/tv/tif/index.html
https://github.com/googlesamples/androidtv-sample-inputs

https://github.com/pipelka/roboTV
https://github.com/TorrentTV/LiveChannels
https://github.com/Fleker/CumulusTV
https://github.com/notz/iptv-live-channels

MfG ;-)

**Comment by sreichholf** [comment]
generally yes, but at the moment I barely have time to do any work on dreamDroid

-----Ursprüngliche Nachricht-----
Von: chemstar <notifications@github.com>
Gesendet: Sam 17 Oktober 2015 11:07
An: sreichholf/dreamDroid <dreamDroid@noreply.github.com>
Betreff: [dreamDroid] any plans to support android tv (#73)

hi stephan, do you have any plans to support android tv's channels feature? 
it would be great addition to dreamdroid when some channels/boquets could be selected and exported to android tv's channels. as i could see dreamdroid already include a lot of the needed code (complete framework for channels/boquets/epg etc. handling). 

some additional informations (if needed/wanted):
https://developer.android.com/training/tv/tif/index.html
https://github.com/googlesamples/androidtv-sample-inputs

https://github.com/pipelka/roboTV
https://github.com/TorrentTV/LiveChannels
https://github.com/Fleker/CumulusTV
https://github.com/notz/iptv-live-channels

MfG ;-)

**Comment by sreichholf** [comment]
Work has started ;). I'll open another issue just for me to keep track of what could possibly be built into the tv-version of dreamDroid.
