### ISSUE TITLE
API-Level 22 target (master branch) will not work with material-dialogs greater than 7.5.5

### ISSUE THREAD

**Issue by TorstenWK** [sreichholf/dreamDroid#74]
I had downloaded your source code and tried to compile it with the newest version of the AndroidStudio (1.4.1). Unfortunately the version of the material-dialogs library (repository version is 7.9.0 or 7.9.1) will need api-level 23 compat libraries. The last version of the material-dialogs library which works with api-level 22 compat libraries is the 7.5.5. So i downloaded a snapshot from this version and manually build and used this library inside the dreamDroid project --> everything works fine. But this is only a temporary work around.

**Comment by sreichholf** [comment]
you want to use the M branch :)

**Comment by TorstenWK** [comment]
Indeed ... is there any timeline when you will merge the M branch back into master? I do not want to put some time pressure on this, only FMI.

**Comment by sreichholf** [comment]
I think's it's quite stable so i think there's actually no argument against mergin M into master...

**Comment by TorstenWK** [comment]
I can confirm that. But ok, i only tested the M branch on my Galaxy S2 with Cyanogen 5.1. Runs without problems. And the best --> it will fix this issue. :-)

**Comment by sreichholf** [comment]
merge completed
