### ISSUE TITLE
strange stop of streaming from dbox

### ISSUE THREAD

**Issue by cwittmer** [sreichholf/dreamDroid#79]
Using MXPlayer for viewing streams or recorded movies from dreambox ... but always when clock reaches 10, 20, 30, 40, 50 or 0 min the stream is interrupted (MXPlayer is stopped) ...
I tried MXPlayer separat while accessing a recorded movie via ftp from dbox ... no problem with MXPlayer.
I see this strange behaviour only via dreamDroid and only on Marshmallow ...
Do you have an idea ?

**Comment by sreichholf** [comment]
VLC is alsways worth a try
