### ISSUE TITLE
Can set or edit profile name

### ISSUE THREAD

**Issue by InoPlugs** [sreichholf/dreamDroid#80]
I installed the latest version from the google play store on my Android 6 phone (stock firmware, basically untouched Android 6) and everything works great so far (can connect to my receiver, streaming works, epg works, etc.). However I noticed that I can't set or edit the profile names. I just see the web url of my receivers but the profile name is missing and I can't set or edit it anywhere on the profile settings page. I see following fields (top to bottom): "Einfache Fernbedienung", "Hostname", "Port", "https" and "login", "Benutzer" and "Password", "Streaming", "Host für Streaming", "Encoder zum Streamen nutzen", "Live Port" and "Login" Checkbox" and "Filme Port" and "login" and "https" checkbox.

Thanks for your help!

**Comment by sreichholf** [comment]
Fixed since 379

**Comment by ottmon** [comment]
Thank you Mr sreichholf  for this great apk, I used VU+ and its work very good , its my favorit apk. But with this upgrade 1.2-400 i can t see profil in setting ,so i can t connect my device .

**Comment by ottmon** [comment]
I found it .comment closed
