### ISSUE TITLE
Set android:fastScrollEnabled to 'true'

### ISSUE THREAD

**Issue by chris400** [sreichholf/dreamDroid#88]
Mainly the EPG is almost a massive long list. If this list (and others like search results) get the setting to true would help a lot.
https://developer.android.com/reference/android/widget/AbsListView.html#attr_android:fastScrollEnabled

**Comment by sreichholf** [comment]
We don't use ListView's anymore. It's pretty much all RecyclerViews

**Comment by chris400** [comment]
Is there any chance to get something equal in RecyclerViews?

**Comment by sreichholf** [comment]
implemented in 7585020a431b95f2d07debb566522970d71ec4e3
